version: 2
updates:
  - package-ecosystem: docker
    directory: /images
    schedule:
      interval: weekly
    assignees:
      - bdalpe

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    assignees:
      - bdalpe