name: Container Image Build

on:
  push:
    branches:
      - main
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        dockerfiles: ["entrypoint", "static"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Docker meta
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          ghcr.io/bdalpe/nginx-connect-proxy
        flavor: |
          suffix=-${{ matrix.dockerfiles }},onlatest=true

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v6
      with:
        push: true
        context: "{{defaultContext}}:images/${{ matrix.dockerfiles }}"
        platforms: linux/amd64,linux/arm64
        tags: ${{ steps.meta.outputs.tags }}